In [1]:
import numpy as np

In [2]:
totals = np.genfromtxt('data/clean.csv', delimiter=',')[1:]  # drop header
totals

array([[  1.,   7.,  16., ...,   4.,   3.,  15.],
       [  2.,   5.,   8., ...,   1.,   1.,   5.],
       [  3.,   8.,  16., ...,  19.,  11.,   7.],
       ...,
       [398.,   3.,   0., ...,   7.,   3.,   2.],
       [399.,   4.,   1., ...,   2.,   0.,   3.],
       [400.,   3.,   2., ...,   3.,   6.,   5.]])

In [3]:
votes = totals[:, 1:]
votes

array([[ 7., 16., 10., ...,  4.,  3., 15.],
       [ 5.,  8., 20., ...,  1.,  1.,  5.],
       [ 8., 16.,  6., ..., 19., 11.,  7.],
       ...,
       [ 3.,  0.,  0., ...,  7.,  3.,  2.],
       [ 4.,  1.,  7., ...,  2.,  0.,  3.],
       [ 3.,  2.,  1., ...,  3.,  6.,  5.]])

In [4]:
num_classes = votes.shape[1]
num_classes

9

In [5]:
max_cats = votes.argmax(axis=1)
assert max_cats.shape[0] == votes.shape[0]
max_cats

array([4, 4, 6, 4, 3, 4, 6, 4, 4, 6, 3, 6, 3, 4, 3, 5, 4, 6, 4, 4, 4, 2,
       6, 6, 1, 6, 5, 6, 4, 6, 3, 4, 4, 6, 4, 4, 2, 4, 6, 6, 1, 4, 6, 4,
       4, 4, 8, 1, 8, 6, 3, 6, 7, 6, 4, 4, 1, 5, 6, 3, 6, 6, 4, 6, 6, 7,
       4, 4, 2, 3, 6, 1, 3, 7, 7, 7, 4, 6, 6, 6, 6, 4, 3, 1, 6, 7, 4, 6,
       4, 6, 8, 4, 4, 1, 6, 4, 1, 4, 4, 5, 3, 3, 6, 3, 8, 3, 4, 3, 5, 5,
       6, 3, 2, 5, 5, 3, 4, 2, 6, 3, 5, 2, 6, 8, 6, 6, 7, 6, 6, 1, 8, 6,
       4, 2, 4, 5, 5, 6, 5, 6, 8, 8, 4, 6, 4, 3, 3, 0, 4, 1, 3, 5, 3, 3,
       1, 6, 7, 0, 3, 7, 7, 5, 3, 2, 2, 3, 6, 3, 6, 3, 7, 3, 6, 5, 3, 8,
       4, 4, 6, 8, 6, 2, 4, 4, 5, 2, 4, 3, 2, 3, 2, 2, 8, 6, 3, 3, 6, 6,
       5, 2, 7, 4, 7, 7, 4, 6, 7, 4, 6, 7, 7, 6, 6, 6, 6, 6, 4, 4, 4, 4,
       1, 7, 6, 4, 7, 1, 4, 5, 7, 6, 5, 5, 7, 7, 4, 6, 1, 4, 7, 7, 1, 3,
       5, 1, 7, 1, 4, 5, 4, 6, 5, 8, 7, 7, 6, 7, 6, 4, 4, 7, 7, 7, 8, 6,
       1, 7, 1, 7, 6, 4, 5, 6, 5, 4, 7, 6, 5, 6, 1, 1, 6, 6, 4, 4, 4, 7,
       6, 4, 1, 4, 1, 6, 5, 4, 4, 6, 1, 6, 1, 5, 2,

In [6]:
one_hot = np.eye(num_classes)[max_cats]
print(one_hot[0])
assert one_hot[0, 4] == 1
one_hot

[0. 0. 0. 0. 1. 0. 0. 0. 0.]


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [7]:
x, y = totals[:, 0], one_hot
x, y

(array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
         23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
         34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
         45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
         56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
         67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
         78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
         89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
        100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
        122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
        133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
        144., 145., 146., 147., 148., 

In [8]:
emotions = ['amazement', 'solemnity', 'tenderness', 'nostalgia', 'calmness', 'power', 'joyful_activation', 'tension', 'sadness']

In [21]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, random_split, Dataset
import torchaudio

In [56]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [16]:
waveform, sample_rate = torchaudio.load('/datasets/memories/SongEmotionDataset/1.mp3')

In [39]:
waveform, sample_rate, waveform.shape

(tensor([[ 0.0000,  0.0000,  0.0000,  ..., -0.0007, -0.0024, -0.0029],
         [ 0.0000,  0.0000,  0.0000,  ..., -0.0011, -0.0029, -0.0033]]),
 44100,
 torch.Size([2, 2647296]))

In [38]:
mono = torch.mean(waveform, dim=0).unsequeeze(0)
mono.shape, mono

(torch.Size([2647296]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0009, -0.0027, -0.0031]))

In [52]:
# settings
n_mfcc = 40
hidden_dim = 128
rnn_layers = 2

In [53]:
class SongEmotionDataset(Dataset):
    """
    Song Emotion Dataset. Uses librosa to process mp3 files.
    Takes first 20 seconds, and samples every 10 to get processed audio tensor.
    """

    def __init__(self, x, y, transform=None):
        """
        Args:
            mp3: list of paths to mp3 files
            labels: list of labels
        """
        self.x = x
        self.y = y
        self.cache = {}
        self.transform = torchaudio.transforms.MFCC(44100, n_mfcc)
        
    def __len__(self):
        return len(self.x)

    def __getitem__(self, index):
        waveform, sample_rate = torchaudio.load(f'/datasets/memories/SongEmotionDataset/{int(x[index])}.mp3')
        mono_waveform = torch.mean(waveform, dim=0)
        return self.transform(mono_waveform).transpose(1, 0)

dataset = SongEmotionDataset(x, y)

In [54]:
traindata, testdata = random_split(dataset, [round(len(dataset)*.8), round(len(dataset)*.2)])

In [55]:
test = traindata[0]
print(test.shape)

torch.Size([13237, 40])


In [ ]:
train_loader = DataLoader(traindata, batch_size=16, shuffle=True, num_workers=2)

In [57]:
model = nn.LSTM(n_mfcc, hidden_dim, rnn_layers).to(device)

In [ ]:
epochs = 10

for epoch in range(epochs):
    running_loss = 0.0